name: scrape_cuaca

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:
    
jobs:
  cuaca-scrape:
    runs-on: Windows-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2   
    - name: Install packages
      run: |
        install.packages("rvest", dependencies = TRUE)
        install.packages("rlang", dependencies = TRUE)
        install.packages("mongolite")
      shell: Rscript {0} 
    - name: Scrape Data Cuaca Harian BMKG
      run: Rscript cuaca_today_scrap.R
